apiVersion: apps/v1
kind: Deployment
metadata:
  name: exampledeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      example: deploymentfornginx
  template:
    metadata:
      labels:
        example: deploymentfornginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.8.1
          ports:
            - containerPort: 80
  strategy:
    type: Recreate
