apiVersion: v1
#副本控制器
kind: ReplicationController
metadata:
  name: mysql
spec:
  # 实例的数量
  replicas: 1
  selector:
    # Pod名称
    app: mysql
  template:
    metadata:
      # Pod副本名称对应selector
      labels:
        app: mysql
    spec:
      containers:    # Pod内容定义部分
      - name: mysql  # 容器的名称
        image: mysql # 容器的镜像
        ports:
        - containerPort: 3306 ## 暴露端口
        env: ##注入到容器内的环境变量
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"