apiVersion: batch/v1
kind: Job
metadata:
  name: examplejobv3
spec:
  completions: 11
  parallelism: 4
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: examplejobcontainer
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sh','-c']
          args: ['echo "Start Job!"; sleep 30; echo "Job Done!"']
