apiVersion: batch/v1betal
kind: CronJob
metadata:
  name: exampleCronJob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: examplejobcontainer
            image: busybox
            imagePullPolicy: IfNotPresent
            command: ['sh','-c']
            args: ['echo "Start Job!"; sleep 30; echo "Job Done!"']
