apiVersion: v1
kind: Service
metadata:
  name: exampleclusteripservice
spec:
  selector:
      example: exampleforservice
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  type: ClusterIP
      
