apiVersion: v1
kind: Service
metadata:
  name: examplenodeportservice
spec:
  selector:
      example: exampleforservice
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
      nodePort: 30001
  type: NodePort
      
