apiVersion: v1
kind: Service
metadata:
  name: exampleheadlessservice
spec:
  selector:
      example: exampleforservice
  clusterIP: None
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  type: ClusterIP
      
